#application configuration
spring:
  application:
    name: ExpensManager-backend
#datasource configuration
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  #JPA Configuration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
 #H2 database Configuration
  h2:
    console:
      enabled: true
      path: /h2-console

